/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Encryption */

#ifndef _Included_Encryption
#define _Included_Encryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Encryption
 * Method:    decrypt
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_Encryption_decrypt
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     Encryption
 * Method:    encrypt
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_Encryption_encrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
